"""Generate the band-aid archival script.

After the durable supervisor is live and the fleet has cut over to it,
the pile of ad-hoc ``~`` scripts that started runners on the login node /
borrowed holder jobs should be moved out of the way so nobody re-runs
them by accident. This generates a script that moves them to
``~/.old/<timestamp>/`` — reversible, non-destructive.

IMPORTANT: the generated script is NOT run by this package. The operator
runs it by hand AFTER cutover, because the live runners still depend on
some of these scripts until then. The script itself only ``mv``s files
that exist and never touches a runner install dir or a SLURM job.
"""

from __future__ import annotations

# The band-aid scripts known to live in ``~`` (verified 2026-06-25).
# Only files that exist are moved; the rest are reported and skipped.
_BANDAID_SCRIPTS = (
    "start_runner.sh",
    "start_runner_fg.sh",
    "relaunch_all.sh",
    "relaunch_runners_shard.sh",
    "relaunch_monitor.sh",
    "probe-runner.sh",
    "diag_runners.sh",
    "archive-runner.sh",
)


def build_archive_script(*, home: str = "~") -> str:
    """Return a non-destructive archival script for the ``~`` band-aids.

    Moves each known band-aid script (if present) into
    ``<home>/.old/<UTC-timestamp>/``. Reports what it moved and what was
    already gone. Never deletes, never touches runner install dirs or
    SLURM jobs.
    """
    files = " \\\n  ".join(_BANDAID_SCRIPTS)
    return f"""#!/usr/bin/env bash
# scitex-ci band-aid archival (generated by scitex_hpc.ci_runners).
# Run BY HAND, on the cluster, AFTER the durable supervisor is live and
# the fleet has cut over. Non-destructive: moves to .old/<ts>/, never rm.
set -uo pipefail

HOME_DIR="{home}"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
DEST="$HOME_DIR/.old/$TS"
mkdir -p "$DEST"
echo "archiving band-aid scripts -> $DEST"

BANDAIDS=(
  {files}
)

moved=0
for f in "${{BANDAIDS[@]}}"; do
  src="$HOME_DIR/$f"
  if [ -e "$src" ]; then
    mv "$src" "$DEST/" && echo "  moved $f" && moved=$((moved+1))
  else
    echo "  (already gone) $f"
  fi
done
echo "archived $moved file(s) to $DEST"
echo "NOTE: runner install dirs under the CI base were NOT touched."
"""
