"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

WHAT THIS GATE IS FOR, stated because it decides how it must behave: it goes RED
when a peer package renames or moves a module this package imports
(`scitex_io._load_cache` -> `scitex_io._loading._load_cache` went undetected for
weeks). A check that skips on ImportError reports that exact event as green, so
skipping is not a neutral default here -- it is the failure mode.

Which is why the modules are split by DECLARED-vs-OPTIONAL rather than treated
alike:

- DECLARED in [project].dependencies -> a hard runtime dependency. Absent means
  the install is BROKEN, so the import is unconditional and the suite goes red.
- OPTIONAL (dev/docs extras only) -> a lean install legitimately lacks it, so
  `pytest.importorskip` is correct. It is still a real check when present.

The split is READ FROM pyproject.toml at test time rather than hardcoded, so
moving a dependency between `dependencies` and an extra changes the strictness
automatically and the two cannot drift apart.
"""

import importlib
import pathlib
import tomllib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_config._ecosystem",
    "scitex_dev.jobs",
    "scitex_ssh",
]
# ===== END AUTO-GENERATED =====


_PYPROJECT = pathlib.Path(__file__).resolve().parents[2] / "pyproject.toml"


def _dependency_specs() -> list[str]:
    """Raw [project].dependencies strings.

    Reads the file rather than the installed metadata on purpose: metadata
    survives the source vanishing, so it answers "was this ever installed?"
    rather than "does this package declare it?".
    """
    data = tomllib.loads(_PYPROJECT.read_text(encoding="utf-8"))
    return list(data.get("project", {}).get("dependencies", []))


def _is_unconditional(spec: str) -> bool:
    """False when the spec carries a PEP 508 environment marker."""
    return ";" not in spec


def _distribution_name(spec: str) -> str:
    dist = spec.split(";")[0]
    for sep in ("==", ">=", "<=", "~=", "!=", ">", "<", "[", " "):
        dist = dist.split(sep)[0]
    return dist.strip().replace("-", "_")


def _declared_distributions() -> set[str]:
    """Dependencies that must import UNCONDITIONALLY on every interpreter.

    A spec carrying an ENVIRONMENT MARKER is deliberately excluded. Marker
    dependencies are a THIRD class, not a variant of declared:

        tomli>=2.0; python_version < "3.11"

    is declared, and LEGITIMATELY ABSENT on 3.12 — behaving exactly as
    specified. Treating it as declared would hard-import it and fail the suite
    for a dependency doing the right thing, which is the strict pole of the
    same both-poles-are-bugs mistake this file exists to avoid.

    Excluded specs fall to the skippable path, whose root-skip +
    full-path-hard-import is already the correct behaviour for them: absence
    may be legitimate on this interpreter, but a PRESENT root with a broken
    path is still a failure.

    Measured by scitex-dev across the fleet: 1 of 531 dependency specs in 18
    repos carries a marker. That density is exactly what survives review and
    fails later, which is why this is handled while it cannot yet bite here.
    """
    return {
        _distribution_name(spec)
        for spec in _dependency_specs()
        if _is_unconditional(spec)
    }


def _is_declared(module_name: str) -> bool:
    return module_name.split(".")[0] in _declared_distributions()


DECLARED_IMPORTS = sorted(m for m in CROSS_PACKAGE_IMPORTS if _is_declared(m))
OPTIONAL_IMPORTS = sorted(m for m in CROSS_PACKAGE_IMPORTS if not _is_declared(m))


def test_pyproject_is_readable_for_the_split():
    """CONTROL: if pyproject moved, every module would silently read as optional."""
    # Arrange
    path = _PYPROJECT
    # Act
    exists = path.is_file()
    # Assert
    assert exists, f"{path} not found; the declared/optional split cannot be trusted"


def test_at_least_one_import_is_declared():
    """CONTROL: an empty declared set would make every check skippable again.

    This is the guard against the gate quietly reverting to the state this file
    was rewritten to fix -- all-optional means nothing can fail.
    """
    # Arrange
    declared = DECLARED_IMPORTS
    # Act
    count = len(declared)
    # Assert
    assert count > 0, f"no cross-package import resolved as declared: {CROSS_PACKAGE_IMPORTS}"


def test_every_dependency_spec_yields_a_distribution_name():
    """CONTROL: a spec the parser cannot read must FAIL, never be demoted.

    An unparsed spec would silently produce an empty name, fall out of the
    declared set, and land in the permissive pole — restoring the skip-everything
    behaviour while the file still LOOKS rigorous. Unparseable is not optional,
    the same way unreadable is not absent.
    """
    # Arrange
    specs = _dependency_specs()
    # Act
    unparsed = [s for s in specs if not _distribution_name(s)]
    # Assert
    assert unparsed == [], f"could not extract a distribution name from: {unparsed}"


def test_a_marker_spec_is_not_unconditional():
    """The classifier itself, exercised on a real marker spec.

    Asserted against a SYNTHETIC input rather than this repo's dependencies,
    which currently carry no markers — a guard that only ever evaluates an empty
    list has not been observed working. This is scitex-dev's measured case:
    1 of 531 specs across 18 repos, `tomli` on Python < 3.11.
    """
    # Arrange
    spec = 'tomli>=2.0; python_version < "3.11"'
    # Act
    unconditional = _is_unconditional(spec)
    # Assert
    assert unconditional is False


def test_a_marker_spec_still_yields_its_distribution_name():
    """Excluding it must not mean failing to parse it — those are different states."""
    # Arrange
    spec = 'tomli>=2.0; python_version < "3.11"'
    # Act
    name = _distribution_name(spec)
    # Assert
    assert name == "tomli"


def test_a_plain_spec_is_unconditional():
    """CONTROL: the predicate must not reject everything.

    Without this, `return False` would satisfy the two tests above and demote
    every dependency to skippable — the permissive pole, silently.
    """
    # Arrange
    spec = "scitex-config>=0.3.0"
    # Act
    unconditional = _is_unconditional(spec)
    # Assert
    assert unconditional is True


def test_no_declared_dependency_of_this_repo_carries_a_marker():
    """Today's state, stated so a future marker addition is a visible change."""
    # Arrange
    specs = _dependency_specs()
    # Act
    conditional = [s for s in specs if not _is_unconditional(s)]
    # Assert
    assert conditional == []


def test_every_import_is_classified():
    """No module may fall outside both buckets."""
    # Arrange
    expected = sorted(CROSS_PACKAGE_IMPORTS)
    # Act
    classified = sorted(DECLARED_IMPORTS + OPTIONAL_IMPORTS)
    # Assert
    assert classified == expected


@pytest.mark.parametrize("module_name", DECLARED_IMPORTS)
def test_declared_dependency_imports_without_skipping(module_name):
    """A declared runtime dependency must import. No skip: absent == broken install."""
    # Arrange
    name = module_name
    # Act
    module = importlib.import_module(name)
    # Assert
    assert module is not None


@pytest.mark.parametrize("module_name", OPTIONAL_IMPORTS)
def test_optional_peer_imports_when_present(module_name):
    """Absent peer -> skip. Present peer with a broken path -> FAIL.

    The skip is taken on the ROOT, and the full dotted path is then imported
    HARD. That distinction is the whole point: `importorskip` on the full path
    swallows ModuleNotFoundError, and a renamed submodule
    (`scitex_io._load_cache` -> `scitex_io._loading._load_cache`) raises exactly
    that -- so skipping on the full path reports the gate's motivating failure
    as green. Absent peer and broken path are different states; collapsing them
    is the same two-valued mistake as everywhere else.
    """
    # Arrange
    root = module_name.split(".")[0]
    # Act
    pytest.importorskip(root)
    module = importlib.import_module(module_name)
    # Assert
    assert module is not None
