"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

WHAT THIS GATE IS FOR, stated because it decides how it must behave: it goes RED
when a peer package renames or moves a module this package imports
(`scitex_io._load_cache` -> `scitex_io._loading._load_cache` went undetected for
weeks). A check that skips on ImportError reports that exact event as green, so
skipping is not a neutral default here -- it is the failure mode.

Which is why the modules are split by DECLARED-vs-OPTIONAL rather than treated
alike:

- DECLARED in [project].dependencies -> a hard runtime dependency. Absent means
  the install is BROKEN, so the import is unconditional and the suite goes red.
- OPTIONAL (dev/docs extras only) -> a lean install legitimately lacks it, so
  `pytest.importorskip` is correct. It is still a real check when present.

The split is READ FROM pyproject.toml at test time rather than hardcoded, so
moving a dependency between `dependencies` and an extra changes the strictness
automatically and the two cannot drift apart.
"""

import importlib
import pathlib
import tomllib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_config._ecosystem",
    "scitex_dev.jobs",
    "scitex_ssh",
]
# ===== END AUTO-GENERATED =====


_PYPROJECT = pathlib.Path(__file__).resolve().parents[2] / "pyproject.toml"


def _declared_distributions() -> set[str]:
    """Distribution names in [project].dependencies, normalised to module form.

    Reads the file rather than the installed metadata on purpose: metadata
    survives the source vanishing, so it answers "was this ever installed?"
    rather than "does this package declare it?".
    """
    data = tomllib.loads(_PYPROJECT.read_text(encoding="utf-8"))
    declared = data.get("project", {}).get("dependencies", [])
    names = set()
    for spec in declared:
        dist = spec.split(";")[0]
        for sep in ("==", ">=", "<=", "~=", "!=", ">", "<", "[", " "):
            dist = dist.split(sep)[0]
        names.add(dist.strip().replace("-", "_"))
    return names


def _is_declared(module_name: str) -> bool:
    return module_name.split(".")[0] in _declared_distributions()


DECLARED_IMPORTS = sorted(m for m in CROSS_PACKAGE_IMPORTS if _is_declared(m))
OPTIONAL_IMPORTS = sorted(m for m in CROSS_PACKAGE_IMPORTS if not _is_declared(m))


def test_pyproject_is_readable_for_the_split():
    """CONTROL: if pyproject moved, every module would silently read as optional."""
    # Arrange
    path = _PYPROJECT
    # Act
    exists = path.is_file()
    # Assert
    assert exists, f"{path} not found; the declared/optional split cannot be trusted"


def test_at_least_one_import_is_declared():
    """CONTROL: an empty declared set would make every check skippable again.

    This is the guard against the gate quietly reverting to the state this file
    was rewritten to fix -- all-optional means nothing can fail.
    """
    # Arrange
    declared = DECLARED_IMPORTS
    # Act
    count = len(declared)
    # Assert
    assert count > 0, f"no cross-package import resolved as declared: {CROSS_PACKAGE_IMPORTS}"


def test_every_import_is_classified():
    """No module may fall outside both buckets."""
    # Arrange
    expected = sorted(CROSS_PACKAGE_IMPORTS)
    # Act
    classified = sorted(DECLARED_IMPORTS + OPTIONAL_IMPORTS)
    # Assert
    assert classified == expected


@pytest.mark.parametrize("module_name", DECLARED_IMPORTS)
def test_declared_dependency_imports_without_skipping(module_name):
    """A declared runtime dependency must import. No skip: absent == broken install."""
    # Arrange
    name = module_name
    # Act
    module = importlib.import_module(name)
    # Assert
    assert module is not None


@pytest.mark.parametrize("module_name", OPTIONAL_IMPORTS)
def test_optional_peer_imports_when_present(module_name):
    """Absent peer -> skip. Present peer with a broken path -> FAIL.

    The skip is taken on the ROOT, and the full dotted path is then imported
    HARD. That distinction is the whole point: `importorskip` on the full path
    swallows ModuleNotFoundError, and a renamed submodule
    (`scitex_io._load_cache` -> `scitex_io._loading._load_cache`) raises exactly
    that -- so skipping on the full path reports the gate's motivating failure
    as green. Absent peer and broken path are different states; collapsing them
    is the same two-valued mistake as everywhere else.
    """
    # Arrange
    root = module_name.split(".")[0]
    # Act
    pytest.importorskip(root)
    module = importlib.import_module(module_name)
    # Assert
    assert module is not None
