"""Audit conformance — runs `scitex-dev ecosystem audit-all` against
THIS CHECKOUT as a normal pytest test. Originally generated by
`scitex-dev ecosystem install-audit-gate`.

WHY THIS FILE IS DEFENDED — DO NOT "SIMPLIFY" ANY OF IT AWAY
============================================================
A gate that grades the wrong tree, or that skips without saying so, is
worse than no gate: its green is load-bearing and people merge on it.
Three separate ways that happens, all measured, all guarded below.

1. NAMING THE TREE (`path=`)
   `audit_all_for_package(distribution)` takes a distribution NAME, not
   a path. Called with the name alone, scitex-dev has no argument saying
   WHICH tree you meant and resolves one by guessing — its last resort
   being a ``~/proj/<distribution>`` development guess. On the
   self-hosted Spartan runner ``~`` is the operator's real home, so that
   guess lands on a human/agent-writable dev checkout unrelated to the
   commit under test.

   Measured 2026-07-29: identical scitex-dev 0.38.1 gave `via cwd` and
   OPPOSITE VERDICTS on the same repo 16 minutes apart, and CI passed on
   develop while the same commit failed locally.

2. VERIFYING THE ANCHOR (`_verified_repo_root`)
   Passing `path=` is not enough if the anchor itself has drifted. If
   this file is moved, or the layout changes, `parents[2]` silently
   addresses some other directory — and the gate then audits it with
   full confidence. So the anchor is VALIDATED against the package's own
   identity before it is used, and a mismatch FAILS rather than falling
   back.

3. PROBING THE RIGHT THING (`find_spec`, not `which`)
   This file previously skipped on ``shutil.which("scitex-dev") is
   None``. The auditor never invokes that console script: it builds its
   argv as ``[sys.executable, "-m", "scitex_dev", ...]``. So the correct
   question is whether THIS INTERPRETER can import scitex_dev, and the
   script's presence on $PATH is unrelated.

   The two disagree in the common case. Measured 2026-08-20 on
   scitex-compute-04 (on sac's copy of this gate): scitex-dev was
   installed in a venv not on the inherited $PATH, so `which` returned
   None and the gate SKIPPED — while the same interpreter ran
   ``python -m scitex_dev ecosystem audit-all`` to completion, exit 0.
   A skip reads as "1 passed, 1 skipped", which looks like coverage.

   That is a green that cannot go red, and it is the failure this whole
   file exists to prevent, hiding one level up in the skip condition.

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing without the
audit corpus available locally. CI for release branches MUST NOT set
this — drift goes silent.
"""

from __future__ import annotations

import importlib.util
import inspect
import sys
import tomllib
from pathlib import Path

import pytest

_DISTRIBUTION = "scitex-hpc"

# This file is tests/develop/test_audit.py, so parents[2] is the checkout —
# NOT parents[1] as in the helper's docstring example, which is written for a
# test living directly in tests/. Anchored on __file__, never on $HOME, CWD or
# an installed location: those answer "where is *a* checkout of this package on
# this disk?", which is not the question a gate asks. It asks "the tree I am
# running against".
_REPO_ROOT = Path(__file__).resolve().parents[2]


class WrongTreeError(AssertionError):
    """The candidate root is not this package's checkout."""


def _verified_repo_root(root: Path | None = None) -> Path:
    """Return the checkout THIS TEST FILE lives in, or fail loudly.

    A validator, not a formality. If the anchor ever stops pointing at
    scitex-hpc's repo root — a moved test file, a changed layout — we must
    NOT fall back to a guess and audit some other tree. That is the exact
    defect this file exists to prevent, so: fail, naming what was found.
    Never substitute silently.

    `root` is a parameter rather than a hardcoded read of the module global
    ONLY so the guard can be exercised against a real foreign checkout (see
    test_verified_repo_root_rejects_a_different_real_checkout). Production
    callers pass nothing and get the __file__ anchor. Raising a typed error
    rather than calling pytest.fail keeps the function testable — pytest.fail
    is not catchable as an ordinary exception by design.
    """
    root = _REPO_ROOT if root is None else root
    pyproject = root / "pyproject.toml"
    if not pyproject.is_file():
        raise WrongTreeError(
            f"cannot locate the checkout under test: no pyproject.toml at "
            f"{pyproject}. This gate refuses to fall back to a "
            f"~/proj/{_DISTRIBUTION} guess — that would audit a tree "
            f"unrelated to the commit under test. Fix the _REPO_ROOT anchor "
            f"in {__file__}."
        )
    declared = (tomllib.loads(pyproject.read_text()).get("project") or {}).get("name")
    if declared != _DISTRIBUTION:
        raise WrongTreeError(
            f"the tree at {root} declares [project] name={declared!r}, "
            f"not {_DISTRIBUTION!r} — so it is NOT this package's checkout. "
            f"Refusing to audit it: a gate that grades the wrong tree reports "
            f"a confident pass/fail about source it never read."
        )
    return root


@pytest.fixture
def scitex_dev_audit():
    """The auditor callable, or a skip/failure that says which it is.

    Skips ONLY when the module is genuinely unavailable — the one
    condition the auditor cannot survive. `importlib.util.find_spec`
    rather than a bare try/import, so that an ImportError raised from
    INSIDE scitex_dev (a real breakage) still propagates instead of
    being read as absence.
    """
    if importlib.util.find_spec("scitex_dev") is None:
        pytest.skip(
            "scitex_dev is not importable by this interpreter "
            f"({sys.executable}) — add `scitex-dev[cli-audit]` to "
            "[project.optional-dependencies.dev]. Note this is about the "
            "MODULE, not the `scitex-dev` console script: the auditor runs "
            "`sys.executable -m scitex_dev` and never looks at $PATH."
        )
    from scitex_dev.testing import audit_all_for_package

    if "path" not in inspect.signature(audit_all_for_package).parameters:
        pytest.fail(
            "installed scitex-dev's audit_all_for_package() has no `path` "
            "parameter, so this gate cannot name the tree under test and "
            "would silently audit a ~/proj guess instead. Upgrade to "
            "scitex-dev>=0.31.1, the release where `path=` first exists. "
            "Failing loudly rather than auditing the wrong checkout."
        )
    return audit_all_for_package


_FOREIGN_DISTRIBUTION = "scitex-agent-container"


@pytest.fixture
def foreign_checkout(tmp_path):
    """A real, well-formed Python package of a DIFFERENT distribution.

    A bare tmp_path is NOT an adequate negative control for the identity
    guard: it trips the missing-pyproject branch and never exercises the
    name comparison, which is the check that actually distinguishes "some
    other checkout on this disk" from "the tree under test". The failure
    mode being guarded against is a WELL-FORMED sibling repo, so the
    control has to be one.

    Constructed rather than pointed at a hardcoded sibling path, so the
    test does not depend on another repo existing on the machine — that
    dependency would make it skip or error on a clean CI runner, which is
    the not-really-running defect this file was rewritten to remove.
    """
    foreign = tmp_path / _FOREIGN_DISTRIBUTION
    (foreign / "src").mkdir(parents=True)
    (foreign / "pyproject.toml").write_text(
        f'[project]\nname = "{_FOREIGN_DISTRIBUTION}"\nversion = "0.1.0"\n'
    )
    return foreign


@pytest.fixture
def foreign_checkout_error(foreign_checkout):
    """The WrongTreeError raised when the guard is shown a foreign tree."""
    with pytest.raises(WrongTreeError) as excinfo:
        _verified_repo_root(foreign_checkout)
    return excinfo.value


def test_verified_repo_root_accepts_this_checkout():
    # Arrange: the anchor is the module-level __file__ resolution.
    expected = _REPO_ROOT
    # Act
    resolved = _verified_repo_root()
    # Assert
    assert resolved == expected


def test_verified_repo_root_rejects_a_different_real_checkout(foreign_checkout):
    # Arrange: foreign_checkout is a valid package of another distribution.
    candidate = foreign_checkout
    # Act / Assert — raising IS the behaviour under test.
    # Assert
    with pytest.raises(WrongTreeError):
        _verified_repo_root(candidate)


def test_rejection_message_names_the_distribution_actually_found(
    foreign_checkout_error,
):
    # Arrange
    message = str(foreign_checkout_error)
    # Act
    found = _FOREIGN_DISTRIBUTION in message
    # Assert
    assert found


def test_rejection_message_names_the_distribution_expected(foreign_checkout_error):
    # Arrange
    message = str(foreign_checkout_error)
    # Act
    named = _DISTRIBUTION in message
    # Assert
    assert named


def test_verified_repo_root_rejects_a_tree_with_no_pyproject(tmp_path):
    # Arrange: a directory that is not a Python package at all.
    candidate = tmp_path
    # Act / Assert — raising IS the behaviour under test.
    # Assert
    with pytest.raises(WrongTreeError):
        _verified_repo_root(candidate)


def test_audit_all_clean(scitex_dev_audit):
    # Arrange — resolve and VALIDATE the tree before naming it.
    repo_root = _verified_repo_root()

    # Act — `path` is REQUIRED in practice even though it defaults to None.
    # It is `_resolve_repo_root` step 1 and is AUTHORITATIVE: it short-circuits
    # every guess, so the header reads `via explicit` and the subject is
    # deterministic.
    result = scitex_dev_audit(_DISTRIBUTION, path=repo_root)

    # Assert — audit_all_for_package returns None on a clean audit and raises
    # AssertionError on any unexpected finding, so reaching here with result
    # None means clean.
    assert result is None
