"""Render a tunnel/service supervisor shell script from a profile.

Pure string generation — no subprocess, no network, fully unit-testable
(same discipline as :mod:`scitex_hpc.ci_runners._supervisor`). The
generated script:

  1. Takes a ``flock`` on the profile's lockfile so only one supervisor
     per (service) runs at a time; a second invocation logs "already
     running" and exits 0 without double-launching.
  2. Runs the sentinel keep-alive loop
     ``while [ -f SENTINEL ]; do <launch>; sleep BACKOFF; done`` — the
     launch command blocks while the service is alive, and the loop
     relaunches it whenever it exits, for as long as the sentinel exists.
     Deleting the sentinel is the clean-shutdown signal.
  3. Appends a timestamped line to the heartbeat log on every start
     attempt and every exit/restart, for post-hoc blip forensics.
  4. Runs a background health watcher that periodically probes the
     configured endpoint (``curl`` by default, injectable via the
     profile). A live PID whose endpoint is dead counts as unhealthy and
     is killed, so the keep-alive loop restarts it — we health-check the
     ENDPOINT, not the PID.
"""

from __future__ import annotations

from ._profile import TunnelSupervisorProfile

_HEADER = "#!/usr/bin/env bash"


def render_supervisor_script(profile: TunnelSupervisorProfile) -> str:
    """Return the self-contained supervisor bash script for ``profile``.

    The script is idempotent w.r.t. the sentinel (create it before / around
    invocation) and safe to launch repeatedly — the flock guard makes a
    redundant invocation a no-op instead of a double-launch.
    """
    p = profile
    probe = p.health_probe()
    # Service pidfile derived from the lockfile path so the background
    # health watcher and the main loop share the current child PID without
    # an extra profile field (a subshell can't see a parent shell var).
    return f"""{_HEADER}
# scitex-hpc tunnel/service supervisor for '{p.name}'
# Generated by scitex_hpc.tunnel_supervisor.render_supervisor_script.
# Runs the launch command under a sentinel keep-alive loop, single-instanced
# by flock, health-checking the ENDPOINT (not the PID) so a live process
# behind a wedged tunnel is restarted. Delete the sentinel to shut down.
set -uo pipefail

NAME="{p.name}"
SENTINEL="{p.sentinel_path}"
LOCKFILE="{p.lockfile_path}"
LOG="{p.log_path}"
PIDFILE="{p.lockfile_path}.svcpid"
POLL_INTERVAL={p.poll_interval}
RESTART_BACKOFF={p.restart_backoff}

mkdir -p "$(dirname "$SENTINEL")" "$(dirname "$LOCKFILE")" \\
         "$(dirname "$LOG")" 2>/dev/null || true

log() {{ echo "[$(date -u +%FT%TZ)] $NAME: $*" >> "$LOG"; }}

# Endpoint health probe: exits 0 iff the service endpoint is healthy.
# Injectable via the profile; defaults to a curl against the health URL.
health_probe() {{ {probe}; }}

# --- single-instance guard (flock) -----------------------------------
# fd 9 holds the lock for the lifetime of this process. A second
# invocation cannot take it (-n = non-blocking) and exits WITHOUT
# launching the service, so the tunnel is never double-started.
exec 9>"$LOCKFILE"
if ! flock -n 9; then
  log "another supervisor holds $LOCKFILE; not double-launching, exiting"
  exit 0
fi

log "supervisor up (poll=${{POLL_INTERVAL}}s backoff=${{RESTART_BACKOFF}}s)"

# Clean-shutdown: drop the sentinel and kill the current service child so
# the loop's next check exits promptly on TERM/INT (e.g. systemd stop).
_shutdown() {{
  rm -f "$SENTINEL"
  if [ -f "$PIDFILE" ]; then kill "$(cat "$PIDFILE" 2>/dev/null)" 2>/dev/null || true; fi
}}
trap _shutdown TERM INT

# --- health watcher (background) -------------------------------------
# Every POLL_INTERVAL it probes the ENDPOINT. If the current service PID
# is alive but the endpoint is dead, it kills the PID -> the keep-alive
# loop restarts it. This is the "live PID, dead endpoint = unhealthy"
# contract: we never trust the PID alone.
_watch_health() {{
  while [ -f "$SENTINEL" ]; do
    sleep "$POLL_INTERVAL"
    [ -f "$SENTINEL" ] || break
    [ -f "$PIDFILE" ] || continue
    local svc
    svc="$(cat "$PIDFILE" 2>/dev/null)"
    [ -n "$svc" ] || continue
    kill -0 "$svc" 2>/dev/null || continue   # no live child -> loop handles it
    if ! health_probe; then
      log "health check FAILED (endpoint dead, PID $svc alive) -> restarting"
      kill "$svc" 2>/dev/null || true
    fi
  done
}}
_watch_health &
WATCH_PID=$!

# --- sentinel keep-alive loop ----------------------------------------
while [ -f "$SENTINEL" ]; do
  log "starting service: {p.launch_command}"
  {p.launch_command} &
  SVC_PID=$!
  echo "$SVC_PID" > "$PIDFILE"
  wait "$SVC_PID"
  rc=$?
  rm -f "$PIDFILE"
  log "service exited rc=$rc; restart in ${{RESTART_BACKOFF}}s"
  [ -f "$SENTINEL" ] || break
  sleep "$RESTART_BACKOFF"
done

kill "$WATCH_PID" 2>/dev/null || true
log "supervisor loop exiting (sentinel gone)"
"""
