"""Deploy the config-driven HPC login-node guard (profile-based).

Background (incidents, 2026-07-01)
----------------------------------
Two login-node abuse vectors on UniMelb Spartan:

  1. An agent ran the TeX toolchain (``pdflatex``/``latexmk``) over SSH on
     a **login node** — heavy compute that HPC policy strictly prohibits
     (admins kill it and can sanction the whole account).
  2. Agents ran recursive ``du``/``find`` over the GPFS project tree
     (``/data/...``) on login nodes, stressing the metadata disks (reads
     as a DoS to storage), which drew repeated admin complaints and fed
     the 8M-file quota pressure.

What the guard does
-------------------
The guard is now **GENERALIZED** to any HPC site via a
:class:`~scitex_hpc.login_guard.GuardProfile`. It is GENERATED from the
profile by :func:`~scitex_hpc.login_guard.render_guard` (like
``ci_runners`` generates its supervisor shell), not shipped as a static
``.sh``. The generated script defines shell **FUNCTION** overrides
(functions beat both PATH and ``module load``, which a PATH shim cannot):

  * ``heavy_tools`` (the TeX toolchain) refuse on a login node, and
  * ``fswalk_tools`` (``du``/``find``) refuse on a login node ONLY when
    the walk targets a ``protected_path_prefixes`` entry (``/data/``),
    checked against each argument AND ``$PWD`` — scoped, so trivial local
    walks still work.

Both are a **no-op inside a SLURM job** (``$SLURM_JOB_ID`` set) and **on a
compute node**, so the CI runner fleet and all legitimate compute are
unaffected. A ``<name>-tex`` helper wraps a compile in ``srun``.
:data:`~scitex_hpc.login_guard.SPARTAN_PROFILE` ships as the default.

This module is pure string generation + a thin SSH call:
:func:`guard_text` renders the script from a profile,
:func:`build_bashrc` performs the idempotent ``~/.bashrc`` transform
(unit-testable without SSH), and :func:`install` does the actual remote
deployment behind an explicit call (never on import).
"""

from __future__ import annotations

from ._profile import SPARTAN_PROFILE, GuardProfile
from ._render import render_guard

# Where the guard lands on the remote host (mirrors the live deployment).
REMOTE_GUARD_PATH = "~/.scitex/hpc/login-guard.sh"

# The line bash uses to bail out of ~/.bashrc for non-interactive shells.
# We must insert the guard source line ABOVE this so it ALSO applies to
# non-interactive ``ssh host '<cmd>'`` (which is exactly the incident
# vector: ``ssh spartan 'pdflatex ...'``).
_INTERACTIVE_RETURN = "[[ $- != *i* ]] && return"

# Live-deployment anchor: the guard source line is inserted right AFTER
# this Spartan non-interactive libs source line. If absent we fall back to
# prepending near the top (still before the interactive-return guard).
_ANCHOR_SUBSTR = "000_spartan_noninteractive_libs.src"

# Marker comment so the insertion is idempotent (re-running never dupes).
_MARKER = "# >>> scitex-hpc login-node guard >>>"
_MARKER_END = "# <<< scitex-hpc login-node guard <<<"


def guard_text(profile: GuardProfile = SPARTAN_PROFILE) -> str:
    """Return the guard script generated from ``profile``.

    Generated by :func:`render_guard` (default: the Spartan profile), so
    the guard is reproducible from the profile values and trivially
    re-targetable to another HPC site. The Spartan render is behaviorally
    identical to the hand-deployed source of truth (same rc 100, same
    ``[BLOCKED]`` token, same ``$SLURM_JOB_ID`` escape, same login-node
    host match, same ``/data/`` protected-prefix walk guard).
    """
    return render_guard(profile)


def _source_block(remote_path: str = REMOTE_GUARD_PATH) -> str:
    """The idempotent, marker-wrapped source block to splice into bashrc.

    The path is left UNQUOTED in the ``[ -f ... ] && . ...`` test so a
    leading ``~`` is tilde-expanded by bash at source time (a quoted
    ``"~/..."`` would be treated literally). ``REMOTE_GUARD_PATH`` has no
    whitespace, so leaving it unquoted is safe.
    """
    return (
        f"{_MARKER}\n"
        f"# Spartan login-node heavy-compute guard (scitex-hpc, incident 2026-07-01).\n"
        f"# Sourced ABOVE the interactive-return so it also applies to\n"
        f"# non-interactive ``ssh spartan '<cmd>'``. No-op inside SLURM jobs.\n"
        f"[ -f {remote_path} ] && . {remote_path}\n"
        f"{_MARKER_END}"
    )


def build_bashrc(
    bashrc: str,
    *,
    remote_path: str = REMOTE_GUARD_PATH,
) -> str:
    """Return ``bashrc`` with the guard source block idempotently inserted.

    Insertion rules (replicating the live deployment):

      1. If the marker block is already present, replace it in place
         (idempotent — re-running never duplicates the source line).
      2. Else, if the ``000_spartan_noninteractive_libs.src`` anchor line
         is present, insert the block right AFTER it.
      3. Else, prepend the block near the top, but ALWAYS before the
         ``[[ $- != *i* ]] && return`` interactive-return guard so it
         applies to non-interactive SSH commands too.

    Pure string transform — no SSH, no filesystem — so the placement
    logic is unit-testable on its own.
    """
    block = _source_block(remote_path)

    # (1) Idempotent replace of an existing marker block.
    if _MARKER in bashrc and _MARKER_END in bashrc:
        start = bashrc.index(_MARKER)
        end = bashrc.index(_MARKER_END) + len(_MARKER_END)
        return bashrc[:start] + block + bashrc[end:]

    lines = bashrc.splitlines(keepends=True)

    # (2) Anchor after the Spartan non-interactive libs source line.
    anchor_idx = next(
        (i for i, ln in enumerate(lines) if _ANCHOR_SUBSTR in ln), None
    )
    if anchor_idx is not None:
        insert_at = anchor_idx + 1
    else:
        # (3) Fall back to just before the interactive-return guard, else
        # the very top.
        ret_idx = next(
            (i for i, ln in enumerate(lines) if _INTERACTIVE_RETURN in ln),
            None,
        )
        insert_at = ret_idx if ret_idx is not None else 0

    insert_text = block + "\n"
    # Keep a clean blank line after the block if the next line isn't blank.
    if insert_at < len(lines) and lines[insert_at].strip():
        insert_text += "\n"
    lines.insert(insert_at, insert_text)
    return "".join(lines)


def build_install_script(
    *,
    profile: GuardProfile = SPARTAN_PROFILE,
    remote_path: str = REMOTE_GUARD_PATH,
) -> str:
    """Return the remote bash script that deploys the guard safely.

    The generated script (run on the remote host over SSH):

      * writes the vendored guard to ``remote_path`` (mkdir -p its dir)
        and ``chmod +x`` it,
      * backs up ``~/.bashrc`` to ``~/.bashrc.scitex-hpc.bak.<ts>``,
      * computes the new ``~/.bashrc`` via the SAME insertion rules as
        :func:`build_bashrc` (delegated to an embedded python3 one-shot so
        the transform logic is not re-implemented in shell), and
      * ``bash -n``-validates the candidate BEFORE replacing the live
        ``~/.bashrc`` — never installs a syntactically broken profile.

    Pure string generation; :func:`install` feeds it to ``exec_remote``.
    """
    guard = guard_text(profile)
    block = _source_block(remote_path)
    # For the script's filesystem ops a quoted ``"~/..."`` would NOT
    # tilde-expand, so map a leading ``~/`` to ``$HOME/`` for the real
    # write target (the bashrc source line keeps the unquoted ``~`` form).
    script_path = (
        f"$HOME/{remote_path[2:]}"
        if remote_path.startswith("~/")
        else remote_path
    )
    # Heredocs (quoted sentinels) so the guard body and the python helper
    # are passed verbatim, never re-expanded by the outer shell.
    return f"""#!/usr/bin/env bash
# scitex-hpc login-node guard installer (generated). Safe + idempotent.
set -euo pipefail

GUARD_PATH="{script_path}"
GUARD_DIR="$(dirname "$GUARD_PATH")"
mkdir -p "$GUARD_DIR"

cat > "$GUARD_PATH" <<'__SCITEX_GUARD_EOF__'
{guard}__SCITEX_GUARD_EOF__
chmod +x "$GUARD_PATH"
echo "wrote guard -> $GUARD_PATH"

BASHRC="$HOME/.bashrc"
[ -f "$BASHRC" ] || touch "$BASHRC"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
BAK="$BASHRC.scitex-hpc.bak.$TS"
cp -p "$BASHRC" "$BAK"
echo "backed up ~/.bashrc -> $BAK"

CANDIDATE="$(mktemp)"
python3 - "$BASHRC" "$GUARD_PATH" > "$CANDIDATE" <<'__SCITEX_PY_EOF__'
import sys

MARKER = {_MARKER!r}
MARKER_END = {_MARKER_END!r}
ANCHOR = {_ANCHOR_SUBSTR!r}
RET = {_INTERACTIVE_RETURN!r}

bashrc_path, remote_path = sys.argv[1], sys.argv[2]
with open(bashrc_path, encoding="utf-8") as fh:
    bashrc = fh.read()

block = (
{block!r}
)

if MARKER in bashrc and MARKER_END in bashrc:
    start = bashrc.index(MARKER)
    end = bashrc.index(MARKER_END) + len(MARKER_END)
    sys.stdout.write(bashrc[:start] + block + bashrc[end:])
    raise SystemExit

lines = bashrc.splitlines(keepends=True)
anchor_idx = next((i for i, ln in enumerate(lines) if ANCHOR in ln), None)
if anchor_idx is not None:
    insert_at = anchor_idx + 1
else:
    ret_idx = next((i for i, ln in enumerate(lines) if RET in ln), None)
    insert_at = ret_idx if ret_idx is not None else 0

insert_text = block + "\\n"
if insert_at < len(lines) and lines[insert_at].strip():
    insert_text += "\\n"
lines.insert(insert_at, insert_text)
sys.stdout.write("".join(lines))
__SCITEX_PY_EOF__

# Validate BEFORE replacing the live profile — never install a broken ~/.bashrc.
if ! bash -n "$CANDIDATE"; then
  echo "candidate ~/.bashrc failed bash -n; aborting (live profile untouched, backup at $BAK)" >&2
  rm -f "$CANDIDATE"
  exit 1
fi

cp "$CANDIDATE" "$BASHRC"
rm -f "$CANDIDATE"
echo "installed guard source line into ~/.bashrc (idempotent; backup $BAK)"
"""


def install(
    *,
    profile: GuardProfile = SPARTAN_PROFILE,
    host: str = "spartan",
) -> "object":
    """Deploy the guard to ``host`` over SSH (explicit call, never on import).

    Renders the guard from ``profile`` (default: Spartan), copies it to
    ``~/.scitex/hpc/login-guard.sh``, makes it executable, backs up
    ``~/.bashrc``, ``bash -n``-validates a candidate, and idempotently
    inserts the source line ABOVE the interactive-return guard (after the
    Spartan non-interactive libs anchor when present). Returns the
    ``scitex_ssh`` result object.
    """
    from scitex_ssh import exec_remote

    import shlex

    script = build_install_script(profile=profile)
    # shlex.quote (not json.dumps): the script carries the multi-line guard
    # body inside a quoted heredoc; literal-\n escaping would collapse it.
    return exec_remote(host, f"bash -lc {shlex.quote(script)}")
